apiVersion: apps/v1
kind: Deployment
metadata:
  name: aziz-app
  labels:
    app: aziz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aziz-app
  template:
    metadata:
      labels:
        app: aziz-app
    spec:
      containers:
      - name: aziz
        image: azizkhedhiri/aziz-spring:2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: SPRING_JPA_SHOW_SQL
        - name: spring.jpa.hibernate.dialect
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: spring.jpa.hibernate.dialect
        - name: SPRING_DATASOURCE_PASSWORD
          value: mysql